services:
  registry:
    image: registry:3.0.0
    volumes:
      - ./registry/config.yaml:/etc/distribution/config.yml:ro
      - registry_data:/var/lib/registry
    networks:
      - registry_network
    expose:
      - "5000"
    env_file: ".env"

  nginx:
    image: nginx:1.29.7
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./nginx/ssl:/etc/nginx/ssl
      - ./nginx/auth:/etc/nginx/auth
    networks:
      - registry_network
    ports:
      - "80:80"
      - "443:443"
    env_file: ".env"
    depends_on:
      - registry

  docker-manager:
    build: ./DockerManager
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./DockerManager:/app
    networks:
      - registry_network
    expose:
      - "8000"
    env_file: ".env"
    depends_on:
      - nginx

volumes:
  registry_data:

networks:
  registry_network:
    driver: bridge
