services:
  registry:
    image: registry:3.0.0
    environment:
      OTEL_TRACES_EXPORTER: none
    volumes:
      - registry_data:/var/lib/registry
    networks:
      - registry_network
    expose:
      - "5000"

  nginx:
    image: nginx:1.29.7
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./nginx/ssl:/etc/nginx/ssl
      - ./nginx/auth:/etc/nginx/auth
      - ./nginx/logs:/etc/nginx/logs
    networks:
      - registry_network
    depends_on:
      - registry
    ports:
      - "80:80"
      - "443:443"

volumes:
  registry_data:

networks:
  registry_network:
    driver: bridge
