services:
  nginx:
    image: nginx:1.29.7
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./nginx/ssl:/etc/nginx/ssl
      - ./nginx/auth:/etc/nginx/auth
    networks:
      - registry_network
    ports:
      - "80:80"
      - "443:443"

  registry:
    image: registry:3.0.0
    volumes:
      - registry_data:/var/lib/registry
    networks:
      - registry_network
    expose:
      - "5000"
    depends_on:
      - nginx

volumes:
  registry_data:

networks:
  registry_network:
    driver: bridge
