error_log /var/log/nginx/error.log warn;

log_format upstream_time  '$remote_addr - $remote_user [$time_local] '
                          '"$request" $status $body_bytes_sent '
                          '"$http_referer" "$http_user_agent" '
                          'rt="$request_time" uct="$upstream_connect_time" '
                          'uht="$upstream_header_time" urt="$upstream_response_time"';

server {
  listen 80;
  server_name _;

  return 301 https://$host$request_uri;
}

server {
  listen 443 ssl;
  server_name _;

  ssl_certificate /etc/nginx/ssl/selfsigned.crt;
  ssl_certificate_key /etc/nginx/ssl/selfsigned.key;

  client_max_body_size 0;

  access_log /var/log/nginx/upstream_time.log upstream_time;

  location /v2/ {
    auth_basic "Registry";
    auth_basic_user_file /etc/nginx/auth/nginx.htpasswd;

    proxy_set_header Host $http_host;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto $scheme;

    proxy_pass http://registry:5000;
  }
}
