import time
from collections.abc import Mapping
from typing import Any

from passlib.context import CryptContext
import psycopg


password_context = CryptContext(schemes=["bcrypt"], deprecated="auto")

SCHEMA_SQL = """
CREATE TABLE IF NOT EXISTS users (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username TEXT NOT NULL UNIQUE,
    password_hash TEXT NOT NULL,
    role TEXT NOT NULL CHECK (role IN ('researcher', 'datamanager'))
);

CREATE TABLE IF NOT EXISTS selection_requests (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_by_user_id INTEGER NOT NULL REFERENCES users(id),
    title TEXT NOT NULL,
    status TEXT NOT NULL,
    filters_json JSONB NOT NULL DEFAULT '{}'::jsonb,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS selection_items (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    request_id INTEGER NOT NULL REFERENCES selection_requests(id) ON DELETE CASCADE,
    orthanc_study_id TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS approvals (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    request_id INTEGER NOT NULL REFERENCES selection_requests(id) ON DELETE CASCADE,
    decided_by_user_id INTEGER NOT NULL REFERENCES users(id),
    decision TEXT NOT NULL,
    reason TEXT,
    decided_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS request_exports (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    request_id INTEGER NOT NULL UNIQUE REFERENCES selection_requests(id) ON DELETE CASCADE,
    request_hash TEXT,
    reused_from_export_id INTEGER REFERENCES request_exports(id),
    status TEXT NOT NULL CHECK (status IN ('PENDING', 'READY', 'FAILED')),
    export_path TEXT,
    manifest_path TEXT,
    error TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS request_export_items (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    export_id INTEGER NOT NULL REFERENCES request_exports(id) ON DELETE CASCADE,
    orthanc_study_id TEXT NOT NULL,
    orthanc_series_id TEXT NOT NULL,
    orthanc_instance_id TEXT NOT NULL,
    stored_file TEXT NOT NULL,
    linked_file TEXT NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    UNIQUE (export_id, orthanc_instance_id)
);

ALTER TABLE request_exports ADD COLUMN IF NOT EXISTS request_hash TEXT;
ALTER TABLE request_exports ADD COLUMN IF NOT EXISTS reused_from_export_id INTEGER REFERENCES request_exports(id);

CREATE INDEX IF NOT EXISTS idx_request_exports_request_hash
ON request_exports(request_hash);
"""


class Database:
    def __init__(self, connection_info: Mapping[str, str | int]) -> None:
        self.connection_info = dict(connection_info)

    def connect(self) -> psycopg.Connection:
        return psycopg.connect(**self.connection_info)

    def initialize(self, attempts: int = 20, delay_seconds: float = 1.0) -> None:
        last_error: Exception | None = None
        for _ in range(attempts):
            try:
                with self.connect() as conn:
                    with conn.cursor() as cur:
                        cur.execute(SCHEMA_SQL)
                        self._seed_users(cur)
                    conn.commit()
                return
            except psycopg.OperationalError as exc:
                last_error = exc
                time.sleep(delay_seconds)

        raise RuntimeError("Could not connect to Postgres during startup.") from last_error

    def health(self) -> dict[str, bool]:
        with self.connect() as conn:
            with conn.cursor() as cur:
                cur.execute("SELECT 1")
                cur.fetchone()
        return {"ok": True}

    def find_user_by_username(self, username: str) -> dict[str, Any] | None:
        with self.connect() as conn:
            with conn.cursor() as cur:
                cur.execute(
                    """
                    SELECT id, username, password_hash, role
                    FROM users
                    WHERE username = %s
                    """,
                    (username,),
                )
                row = cur.fetchone()

        return self._user_from_row(row)

    def find_user_by_id(self, user_id: int) -> dict[str, Any] | None:
        with self.connect() as conn:
            with conn.cursor() as cur:
                cur.execute(
                    """
                    SELECT id, username, password_hash, role
                    FROM users
                    WHERE id = %s
                    """,
                    (user_id,),
                )
                row = cur.fetchone()

        return self._user_from_row(row)

    def _seed_users(self, cur: psycopg.Cursor) -> None:
        demo_users = (
            ("researcher_demo", "researcher_demo", "researcher"),
            ("datamanager_demo", "datamanager_demo", "datamanager"),
        )
        for username, password, role in demo_users:
            password_hash = password_context.hash(password)
            cur.execute(
                """
                INSERT INTO users (username, password_hash, role)
                VALUES (%s, %s, %s)
                ON CONFLICT (username) DO UPDATE
                SET password_hash = EXCLUDED.password_hash,
                    role = EXCLUDED.role
                """,
                (username, password_hash, role),
            )

    def _user_from_row(self, row: tuple[Any, ...] | None) -> dict[str, Any] | None:
        if row is None:
            return None
        user_id, username, password_hash, role = row
        return {
            "id": user_id,
            "username": username,
            "password_hash": password_hash,
            "role": role,
        }
